local my_language = {
	-- poll one
	poll1_q1 = "Quel genre de serveur souhaiteriez-vous voir?",
	poll1_q2 = "Quelle mise à jour souhaiteriez-vous prioriser sur Extinction?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Mission privée solo ou avec 1-4 amis (comme Payday / Heist / Hitman)",
	poll1_q1_a3 = "Course",
	poll1_q1_a4 = "Murder / Horreur",

	poll1_q2_a1 = "PvE améliorer les zombies/farm",
	poll1_q2_a2 = "Ajouter des évènements sur la map",
	poll1_q2_a3 = "Shop/Troc MAJ",
	poll1_q2_a4 = "Plus de stats RPG / améliorations",

	press_x_to_x = "Appuyez sur %s pour %s~w~.",
	crew = "crew",
	organization = "organisation",
	company = "entreprise",
	discuss_with_npc = "~b~discusser~w~ avec cette personne",
	available_actions = "action disponibles",
	help = "Aide",
	unknown = "Inconnu",
	need_cops_to_do_that = "~r~Il faut au moins %s policiers en ville pour cette action.",
	not_enough_cops = "~r~Il n'y a pas assez de policier en ville.",
	not_enough_of_x = "~r~Vous n'avez pas suffisamment de ~b~%s~r~.",
	not_enough_room_inv = "~r~Vous n'avez plus de place dans votre inventaire.",

	-- Activity
	no_resource_access = "~r~Vous n'avez pas accès à cette ressource.",
	no_required_job = "~r~Vous n'avez pas le métier requis.",
	no_required_orga = "~r~Vous n'avez pas l'organisation requise.",
	no_required_crew = "~r~Vous n'avez pas le crew requis.",
	you_left_the_farming_area = "~r~Vous avez quitté la zone.",
	start_activity = "~g~lancer l'activité",
	stop_activity = "~r~stopper",
	you_gave_up_farm = "~r~Vous avez abandonné.",
	you_need_to_be_close_to_your_vehicle_job = "~r~Vous devez être à côté de votre véhicule de service.",
	incorrect_job_veh = "~r~Votre véhicule métier est incorrect.",
	you_dont_have_knowledge = "~r~Vous n'avez pas les compétences nécessaires.",
	not_enough_items = "~r~Vous n'avez pas suffisamment d'objet.",
	interest_point_for = "Circuit %s",
	you_need_job_outfit = "~r~Et non.\n~w~Procurez-vous une tenue de service à un magasin de vêtements.",
	not_right_rank = "~r~Vous n'avez pas le rang nécessaire.",
	car_spawn_point = "~r~Il y a déjà un véhicule sur la zone d'apparition.",
	no_activity = "~r~Activité introuvable.",
	cant_sell_this_item = "~r~Vous ne pouvez pas vendre cet item.",
	incorrect_price = "~r~Prix incorrect.",
	you_sold_x_for_x = "Vous avez vendu votre ~g~%s. ~b~+1 ~w~à ~b~$%s",
	no_company = "~r~Votre entreprise est introuvable.",
	trade_x_for_x_and_got_x = "Vous avez échangé ~b~%sx %s~w~ contre ~b~%s~w~ et récupéré ~g~%s$~w~.",
	work_limit = "~r~Vous avez franchi la limite de travail.",
	you_got_x = "Vous avez récupéré un ~g~%s. ~b~+1",
	you_processed_x_x = "Vous avez traité votre ~g~%s. ~b~+%s",
	you_sold_x_for_x = "Vous avez vendu votre ~g~%s. ~b~+1 ~w~à ~b~$%s",

	-- Activity: HQ
	get_vehicle = "Sortir le véhicule",
	name_vehicle = "Renommer le véhicule",
	options = "options",
	troc = "troc",
	vehicules = "vehicules",
	store_vehicle = "Ranger votre véhicule",
	invalid_vehicle = "~r~Le véhicule est invalide, il ne peut pas être rangé.",
	invalid_driver = "~r~Vous ne pouvez pas ranger un véhicule qui est piloté par quelqu'un.",
	no_help = "Aucune aide n'est disponible.",
}

AddLanguage("fr", my_language)