local my_language = {
	-- poll one
	poll1_q1 = "Quel genre de serveur souhaiteriez-vous voir?",
	poll1_q2 = "Quelle mise à jour souhaiteriez-vous prioriser sur Extinction?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Mission privée solo ou avec 1-4 amis (comme Payday / Heist / Hitman)",
	poll1_q1_a3 = "Course",
	poll1_q1_a4 = "Murder / Horreur",

	poll1_q2_a1 = "PvE améliorer les zombies/farm",
	poll1_q2_a2 = "Ajouter des évènements sur la map",
	poll1_q2_a3 = "Shop/Troc MAJ",
	poll1_q2_a4 = "Plus de stats RPG / améliorations",

	press_x_to_x = "Appuyez sur %s pour %s~w~.",
	crew = "crew",
	organization = "organisation",
	company = "entreprise",
	discuss_with_npc = "~b~discusser~w~ avec cette personne",
	available_actions = "action disponibles",
	help = "Aide",
	unknown = "Inconnu",
	need_cops_to_do_that = "~r~Il faut au moins %s policiers en ville pour cette action.",
	not_enough_cops = "~r~Il n'y a pas assez de policier en ville.",
	not_enough_of_x = "~r~Vous n'avez pas suffisamment de ~b~%s~r~.",
	not_enough_room_inv = "~r~Vous n'avez plus de place dans votre inventaire.",

	-- Activity
	no_resource_access = "~r~Vous n'avez pas accès à cette ressource.",
	no_required_job = "~r~Vous n'avez pas le métier requis.",
	no_required_orga = "~r~Vous n'avez pas l'organisation requise.",
	no_required_crew = "~r~Vous n'avez pas le crew requis.",
	you_left_the_farming_area = "~r~Vous avez quitté la zone.",
	start_activity = "~g~lancer l'activité",
	stop_activity = "~r~stopper",
	you_gave_up_farm = "~r~Vous avez abandonné.",
	you_need_to_be_close_to_your_vehicle_job = "~r~Vous devez être à côté de votre véhicule de service.",
	incorrect_job_veh = "~r~Votre véhicule métier est incorrect.",
	you_dont_have_knowledge = "~r~Vous n'avez pas les compétences nécessaires.",
	not_enough_items = "~r~Vous n'avez pas suffisamment d'objet.",
	interest_point_for = "Circuit %s",
	you_need_job_outfit = "~r~Et non.\n~w~Procurez-vous une tenue de service à un magasin de vêtements.",
	not_right_rank = "~r~Vous n'avez pas le rang nécessaire.",
	car_spawn_point = "~r~Il y a déjà un véhicule sur la zone d'apparition.",
	no_activity = "~r~Activité introuvable.",
	cant_sell_this_item = "~r~Vous ne pouvez pas vendre cet item.",
	incorrect_price = "~r~Prix incorrect.",
	you_sold_x_for_x = "Vous avez vendu votre ~g~%s. ~b~+1 ~w~à ~b~$%s",
	no_company = "~r~Votre entreprise est introuvable.",
	trade_x_for_x_and_got_x = "Vous avez échangé ~b~%sx %s~w~ contre ~b~%s~w~ et récupéré ~g~%s$~w~.",
	work_limit = "~r~Vous avez franchi la limite de travail.",
	you_got_x = "Vous avez récupéré un ~g~%s. ~b~+1",
	you_processed_x_x = "Vous avez traité votre ~g~%s. ~b~+%s",
	you_sold_x_for_x = "Vous avez vendu votre ~g~%s. ~b~+1 ~w~à ~b~$%s",

	-- Activity: HQ
	get_vehicle = "Sortir le véhicule",
	name_vehicle = "Renommer le véhicule",
	options = "options",
	troc = "troc",
	vehicules = "vehicules",
	store_vehicle = "Ranger votre véhicule",
	invalid_vehicle = "~r~Le véhicule est invalide, il ne peut pas être rangé.",
	invalid_driver = "~r~Vous ne pouvez pas ranger un véhicule qui est piloté par quelqu'un.",
	no_help = "Aucune aide n'est disponible.",

	-- Admin
	show_gamertags = "Show gamertags",
	other_options = "Other options",
	revive = "Revive",
	total_members = "Total members",
	groups_list = "Groups list",
	group_type = "Group type",
	groups_management = "Groups management",
	group_management = "Group management",
	players_list = "Liste des joueurs",
	my_player = "My player",
	player = "Player",
	world = "World",
	main_menu = "Main menu",
	administration = "Administration",
	noclip_speed = "Noclip speed",
	spectate_player = "Spectate the player",
	comeback_here = "Comeback here",
	quicker = "Quicker",
	slower = "Slower",
	you_entered_x_arguments_command = "Vous avez entré %s argument(s) la commande en demande au moins %s.",

	-- Business
	rename_your_company = "~r~Pensez à renommer votre entreprise pour qu'elle soit affichée sur la carte! (pour refresh)",
	business_creation = "Création d'entreprise",
	create_my_company = "Créer mon entreprise",
	business_center = "Centre des entreprises",
	name_of_your_company = "Nom de votre entreprise",
	how_to_create_my_company = "Comment créer mon entreprise?",
	create_my_company_answer = "Ici! Créez votre entreprise, choisissez le nom et vous pourrez commencer à gérer votre business sans aucune intervention extérieure.",
	how_to_manage_my_company = "Comment gérer mon entreprise?",
	manage_my_company_answer = "En étant chef d'entreprise vous pouvez gérer les différentes options auxquelles vous avez accès via ~b~/business~w~. A partir de ce menu vous pourrez modifier votre activité mais aussi personnaliser les ressources ou objets que vous souhaitez fabriquer ou échanger.",
	company_activities_one = "Pour quel type d'activité?",
	company_activities_two = "~b~1.~w~ Production/Farm: créez vous même vos points d'interactions et les ressources que vous utilisez. ~b~2.~w~ Magasins: comme le LTD. ~b~3.~w~ Vente d'objets: cela peut être par exemple la vente de CD, film, livre que vous pourrez produire en illimité et revendre aux joueurs.",
	item_options = "options de l'item",
	items_list = "liste des items",
	select_production_channel = "Choisir le channel de production",
	items_management = "gestion des items",
	activity_options = "options de l'activité",
	create_activity = "créer une activité",
	business_management = "Gestion du business",
	activity_type = "Type de l'activité",
	business_name = "Nom du business",
	business_id = "ID du business",
	production = "Production",
	commercant = "Shop",
	creator = "Créateur",
	item_to_produce = "Nom de l'item produit",
	example_creator_item = "For instance, 'Pacific ocean painting'",
	creating_item = "Fabrication de l'objet",
	make_item = "Produire un objet",
	recommended_to_be_outside_an_interior = "~r~Il est préférable d'être à l'extérieur.",
	warning_change_type_shop = "Attention! Vous ne pouvez changer de type de magasin qu'une seule fois par jour.",
	shop_type = "Type du magasin",
	add_hq_npc = "Ajouter un QG (PNJ)",
	add_sell_point = "Ajouter un point de vente",
	add_process_point = "Ajouter un point de traitement",
	add_collect_point = "Ajouter un point de récolte",
	ltd = "Convenience Store",
	hardware_store = "Quincailler",
	garage = "Garage / LS Custom",
	employee = "Employé",
	ceo = "PDG",
	item_name_incorrect = "Le nom de l'objet est incorrect ou trop long.",
	activity_type_daily_limit = "Vous ne pouvez changer d'activité qu'une seule fois par jour.",
	spot_too_close_other = "Le spot que vous avez sélectionez est trop proche d'un autre de vos spots.",
	spot_too_close_other_point = "Le spot que vous avez sélectionez est trop proche d'un autre circuit.",
	hq_too_close_other_hq = "Le spot que vous avez sélectionez est trop proche d'un autre QG.",
	item_already_used_channel = "L'item que vous avez sélectionnez est déjà utilisé dans votre circuit.",
	incompatible_item = "L'objet que vous avez sélectionnez est incompatible.",
	business_name_invalid = "~r~Le nom de votre business est incorrect.",
	need_to_be_close_gouv = "~r~Vous devez être à côté d'un membre du gouvernement.",
	only_gouv = "~r~Seul un membre du gouvernement peut créer une entreprise",
	you_are_already_ceo = "~r~Vous êtes déjà chef d'une entreprise.",
	you_paid_x_for_company = "Vous avez payé ~g~$%s~w~ pour la création de votre entreprise.",
	business_creation_failed = "~r~La création de votre entreprise a échoué.",
	changed_saved_sync_soon = "~g~Vos changements ont bien été sauvegardés.\n~w~Ces changements seront synchronisés dans quelques minutes.",
	you_changed_your_company_name = "Vous avez modifié le nom de votre entreprise pour ~b~%s~w~.",
	production_item_missing = "~r~Vous n'avez pas indiqué l'objet que vous souhaitez produire.",
	cannot_produce_item_full = "~r~Vous ne pouvez pas produire cet item.\n~w~Vous inventaire est plein.",
	need_x_to_produce = "~r~Vous ne pouvez pas produire cet item.\n~w~Vous n'avez pas les ~r~%s~w~ requis.",
	you_paid_x_to_manufacture_x = "Vous avez payé ~g~$%s~w~ pour la fabrication de ~b~%sx %s~w~.",
}

AddLanguage("fr", my_language)